In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.0.0'

### Constants

In [5]:
tensor = tf.constant([[1,1], [1,1]])

In [7]:
tensor #also prints array now

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [9]:
tensor.shape

TensorShape([2, 2])

In [11]:
tensor.numpy() #directly access array

array([[1, 1],
       [1, 1]])

In [12]:
numpy_tensor = np.array([[1,1],[1,1]])

In [14]:
tf_constant = tf.constant(numpy_tensor)

### Variables

In [15]:
variable = tf.Variable([[1,1], [1,1]])

In [16]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [17]:
variable.numpy()

array([[1, 1],
       [1, 1]])

In [18]:
variable[0, 0].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[100,   1],
       [  1,   1]])>

### Operations

In [19]:
tensor = tf.constant([[1,2],[3,4]])

In [20]:
tensor + 2

<tf.Tensor: id=21, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [21]:
tensor * 5

<tf.Tensor: id=23, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

In [23]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [24]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [25]:
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]])

### Strings

In [27]:
tf_string = tf.constant("Tensorflow")
tf_string

<tf.Tensor: id=25, shape=(), dtype=string, numpy=b'Tensorflow'>

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=10>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=30, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119])>

In [30]:
tf_string_array = tf.constant(["tensorflow", "deep learning", "ai"])

In [31]:
for string in tf_string_array:
    print(string)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'deep learning', shape=(), dtype=string)
tf.Tensor(b'ai', shape=(), dtype=string)
